# Generated by Django 4.1.4 on 2023-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
