# Generated by Django 4.1.4 on 2023-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='vector',
            field=models.JSONField(),
        ),
    ]
