# Generated by Django 4.1.4 on 2023-08-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_image_height_alter_image_vector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='base64',
            new_name='url',
        ),
    ]
