# Generated by Django 4.1.4 on 2023-08-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_rename_base64_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='source',
        ),
    ]
